### ISSUE TITLE
add a build for python like the cpp one and update the readme in a way that anyone can understand it and place the files in the right location

### ISSUE THREAD

**Issue by debojeetjha10** [shivam-51/sublime_text#1]
@shivam-51 can i do it?

**Comment by shivam-51** [comment]
Sure, let me assign this to you. Will this build be Windows dependent or Linux?

**Comment by debojeetjha10** [comment]
ok then let me create two different branches one for linux and one for windows.
does it sounds fair?

**Comment by shivam-51** [comment]
that would be great, yes :)

**Comment by shivam-51** [comment]
Also, add a build for c++ on windows
Result -
c++ on both Windows and Linux
Python on both Windows and Linux

**Comment by debojeetjha10** [comment]
ok!
